In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
train = pd.read_csv('data/train.csv', index_col=0)
train.head()

target  48df886f9  0deb4b6a8  34b15f335  a8cb14b00  2f0771a37  \
ID                                                                             
000d6aaf2  38000000.0        0.0          0        0.0          0          0   
000fbd867    600000.0        0.0          0        0.0          0          0   
0027d6b71  10000000.0        0.0          0        0.0          0          0   
0028cbf45   2000000.0        0.0          0        0.0          0          0   
002a68644  14400000.0        0.0          0        0.0          0          0   

           30347e683  d08d1fbe3  6ee66e115  20aa07010    ...      3ecc09859  \
ID                                                       ...                  
000d6aaf2          0          0          0        0.0    ...            0.0   
000fbd867          0          0          0  2200000.0    ...            0.0   
0027d6b71          0          0          0        0.0    ...            0.0   
0028cbf45          0          0          0        0.0    ...            0.0   
002a68644          0          0          0  2000000.0    ...            0.0   

           9281abeea  8675bec0b  3a13ed79a  f677d4d13  71b203550  137efaa80  \
ID                                                                            
000d6aaf2        0.0        0.0          0          0          0          0   
000fbd867        0.0        0.0          0          0          0          0   
0027d6b71        0.0        0.0          0          0          0          0   
0028cbf45        0.0        0.0          0          0          0          0   
002a68644        0.0        0.0          0          0          0          0   

           fb36b89d9  7e293fbaf  9fc776466  
ID                                          
000d6aaf2          0          0          0  
000fbd867          0          0          0  
0027d6b71          0          0          0  
0028cbf45          0          0          0  
002a68644          0          0          0  

[5 rows x 4992 columns]

In [3]:
X = train.drop('target', axis=1)
y = train.target

In [4]:
from sklearn.decomposition import FactorAnalysis

fa = FactorAnalysis(n_components=50, random_state=42)
X_fa = fa.fit_transform(X)
X_fa

array([[-0.01886857, -0.01938037, -0.01936813, ...,  0.04026556,
        -0.10473984, -0.12211743],
       [-0.01886847, -0.01938024, -0.01936782, ...,  0.0114516 ,
         0.14867645, -0.12505991],
       [-0.0188684 , -0.01938009, -0.0193676 , ..., -0.03525191,
         0.06421761, -0.1443432 ],
       ...,
       [-0.01886892, -0.01938112, -0.01936888, ..., -0.22481366,
        -0.17245079, -0.27400836],
       [-0.0188684 , -0.01938009, -0.01936759, ..., -0.05589693,
         0.05242942, -0.13260685],
       [-0.01886912, -0.01938095, -0.0193683 , ...,  0.87308081,
        -0.80500966,  3.77912178]])

In [5]:
from sklearn.random_projection import SparseRandomProjection

srp = SparseRandomProjection(n_components=50, random_state=42)
X_srp = srp.fit_transform(X)
X_srp

array([[ 0.00000000e+00, -9.86597436e+06, -1.06980445e+07, ...,
        -2.85281186e+06,  0.00000000e+00, -1.30753877e+06],
       [-4.75468644e+06,  4.75468644e+06, -2.37734322e+06, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  1.42640593e+07],
       ...,
       [ 0.00000000e+00, -9.57593849e+06, -6.82059770e+06, ...,
         0.00000000e+00, -4.11125850e+08,  2.02668510e+07],
       [ 0.00000000e+00, -1.78300742e+06,  0.00000000e+00, ...,
        -1.78300742e+06, -1.78300742e+06,  1.78300742e+06],
       [-3.04299932e+07, -2.80526500e+07, -5.46788941e+07, ...,
         1.66414025e+07,  4.58827242e+07, -1.90187458e+07]])

In [6]:
from sklearn.random_projection import GaussianRandomProjection

grp = GaussianRandomProjection(n_components=50, random_state=42)
X_grp = grp.fit_transform(X)
X_grp

array([[ 1.98984205e+04, -1.68966592e+07, -2.87725795e+07, ...,
        -7.05108049e+06,  2.56364676e+07,  1.43737341e+07],
       [ 9.12448574e+06, -3.66896198e+06,  1.89252984e+07, ...,
         1.23405282e+07, -3.03103070e+07,  9.49260651e+06],
       [ 4.97362563e+06,  2.42804867e+06,  2.66562761e+06, ...,
         1.31575020e+06, -2.41291477e+06, -1.07508841e+06],
       ...,
       [ 2.13676725e+07, -5.63305501e+07, -5.51580060e+07, ...,
        -9.96078283e+07, -6.53276959e+07, -9.61493055e+07],
       [-2.62922642e+06,  1.47046789e+06,  4.39879891e+06, ...,
        -5.61532060e+06, -3.93367998e+05,  4.24955277e+05],
       [ 2.78588797e+07, -2.45335554e+07,  2.12276387e+07, ...,
        -4.28778360e+05,  7.79543171e+06,  3.45934222e+07]])

In [7]:
from sklearn.model_selection import train_test_split

X_added = pd.concat([
    pd.DataFrame(X_fa),
    pd.DataFrame(X_srp),
    pd.DataFrame(X_grp),
], axis=1)
print(X_added.shape)

y_log = np.log1p(y)

X_train, X_test, y_train, y_test = train_test_split(
    X_added, y_log, test_size=0.2, random_state=42
)

(4459, 150)


In [8]:
def rmsle_metric(y_test, y_pred): 
    assert len(y_test) == len(y_pred)
    y_test = np.exp(y_test)-1
    y_pred = np.exp(y_pred)-1
    rmsle = np.sqrt(np.mean((np.log(1+y_pred) - np.log(1+y_test))**2))
    return ('RMSLE', rmsle, False)

In [9]:
import lightgbm as lgb

gbm = lgb.LGBMRegressor(
    objective='regression',
    num_leaves=31,
    learning_rate=0.008,
    n_estimators=600
)

gbm.fit(X_train, y_train,
        eval_set=[(X_test, y_test)],
        eval_metric=rmsle_metric,
        early_stopping_rounds=100
)

[1]	valid_0's l2: 2.86577	valid_0's RMSLE: 1.69286
Training until validation scores don't improve for 100 rounds.
[2]	valid_0's l2: 2.85521	valid_0's RMSLE: 1.68974
[3]	valid_0's l2: 2.8437	valid_0's RMSLE: 1.68633
[4]	valid_0's l2: 2.83359	valid_0's RMSLE: 1.68333
[5]	valid_0's l2: 2.82227	valid_0's RMSLE: 1.67996
[6]	valid_0's l2: 2.8116	valid_0's RMSLE: 1.67678
[7]	valid_0's l2: 2.80151	valid_0's RMSLE: 1.67377
[8]	valid_0's l2: 2.79073	valid_0's RMSLE: 1.67055
[9]	valid_0's l2: 2.78077	valid_0's RMSLE: 1.66756
[10]	valid_0's l2: 2.77067	valid_0's RMSLE: 1.66453
[11]	valid_0's l2: 2.76137	valid_0's RMSLE: 1.66174
[12]	valid_0's l2: 2.75079	valid_0's RMSLE: 1.65855
[13]	valid_0's l2: 2.74138	valid_0's RMSLE: 1.65571
[14]	valid_0's l2: 2.73216	valid_0's RMSLE: 1.65292
[15]	valid_0's l2: 2.72323	valid_0's RMSLE: 1.65022
[16]	valid_0's l2: 2.71414	valid_0's RMSLE: 1.64747
[17]	valid_0's l2: 2.70567	valid_0's RMSLE: 1.64489
[18]	valid_0's l2: 2.69699	valid_0's RMSLE: 1.64225
[19]	valid_0

[158]	valid_0's l2: 2.15326	valid_0's RMSLE: 1.4674
[159]	valid_0's l2: 2.15216	valid_0's RMSLE: 1.46702
[160]	valid_0's l2: 2.15097	valid_0's RMSLE: 1.46662
[161]	valid_0's l2: 2.14906	valid_0's RMSLE: 1.46597
[162]	valid_0's l2: 2.14751	valid_0's RMSLE: 1.46544
[163]	valid_0's l2: 2.14683	valid_0's RMSLE: 1.46521
[164]	valid_0's l2: 2.14521	valid_0's RMSLE: 1.46465
[165]	valid_0's l2: 2.14381	valid_0's RMSLE: 1.46418
[166]	valid_0's l2: 2.14179	valid_0's RMSLE: 1.46349
[167]	valid_0's l2: 2.13975	valid_0's RMSLE: 1.46279
[168]	valid_0's l2: 2.13905	valid_0's RMSLE: 1.46255
[169]	valid_0's l2: 2.13755	valid_0's RMSLE: 1.46204
[170]	valid_0's l2: 2.13624	valid_0's RMSLE: 1.46159
[171]	valid_0's l2: 2.13476	valid_0's RMSLE: 1.46108
[172]	valid_0's l2: 2.13405	valid_0's RMSLE: 1.46084
[173]	valid_0's l2: 2.13221	valid_0's RMSLE: 1.46021
[174]	valid_0's l2: 2.12985	valid_0's RMSLE: 1.4594
[175]	valid_0's l2: 2.12839	valid_0's RMSLE: 1.4589
[176]	valid_0's l2: 2.12706	valid_0's RMSLE: 1.45

[322]	valid_0's l2: 1.98647	valid_0's RMSLE: 1.40942
[323]	valid_0's l2: 1.98591	valid_0's RMSLE: 1.40922
[324]	valid_0's l2: 1.98517	valid_0's RMSLE: 1.40896
[325]	valid_0's l2: 1.98512	valid_0's RMSLE: 1.40894
[326]	valid_0's l2: 1.98479	valid_0's RMSLE: 1.40883
[327]	valid_0's l2: 1.98468	valid_0's RMSLE: 1.40879
[328]	valid_0's l2: 1.98399	valid_0's RMSLE: 1.40854
[329]	valid_0's l2: 1.98352	valid_0's RMSLE: 1.40838
[330]	valid_0's l2: 1.98267	valid_0's RMSLE: 1.40807
[331]	valid_0's l2: 1.98228	valid_0's RMSLE: 1.40794
[332]	valid_0's l2: 1.98212	valid_0's RMSLE: 1.40788
[333]	valid_0's l2: 1.9813	valid_0's RMSLE: 1.40759
[334]	valid_0's l2: 1.98101	valid_0's RMSLE: 1.40748
[335]	valid_0's l2: 1.98067	valid_0's RMSLE: 1.40736
[336]	valid_0's l2: 1.98029	valid_0's RMSLE: 1.40723
[337]	valid_0's l2: 1.98023	valid_0's RMSLE: 1.40721
[338]	valid_0's l2: 1.97949	valid_0's RMSLE: 1.40694
[339]	valid_0's l2: 1.97935	valid_0's RMSLE: 1.4069
[340]	valid_0's l2: 1.97916	valid_0's RMSLE: 1.4

[478]	valid_0's l2: 1.94029	valid_0's RMSLE: 1.39294
[479]	valid_0's l2: 1.94007	valid_0's RMSLE: 1.39286
[480]	valid_0's l2: 1.93967	valid_0's RMSLE: 1.39272
[481]	valid_0's l2: 1.93974	valid_0's RMSLE: 1.39275
[482]	valid_0's l2: 1.93987	valid_0's RMSLE: 1.39279
[483]	valid_0's l2: 1.93971	valid_0's RMSLE: 1.39273
[484]	valid_0's l2: 1.93938	valid_0's RMSLE: 1.39262
[485]	valid_0's l2: 1.93907	valid_0's RMSLE: 1.39251
[486]	valid_0's l2: 1.93887	valid_0's RMSLE: 1.39243
[487]	valid_0's l2: 1.93867	valid_0's RMSLE: 1.39236
[488]	valid_0's l2: 1.93882	valid_0's RMSLE: 1.39241
[489]	valid_0's l2: 1.93863	valid_0's RMSLE: 1.39235
[490]	valid_0's l2: 1.93834	valid_0's RMSLE: 1.39224
[491]	valid_0's l2: 1.93828	valid_0's RMSLE: 1.39222
[492]	valid_0's l2: 1.93793	valid_0's RMSLE: 1.3921
[493]	valid_0's l2: 1.93825	valid_0's RMSLE: 1.39221
[494]	valid_0's l2: 1.93817	valid_0's RMSLE: 1.39218
[495]	valid_0's l2: 1.93805	valid_0's RMSLE: 1.39214
[496]	valid_0's l2: 1.9382	valid_0's RMSLE: 1.3

LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
       learning_rate=0.008, max_depth=-1, min_child_samples=20,
       min_child_weight=0.001, min_split_gain=0.0, n_estimators=600,
       n_jobs=-1, num_leaves=31, objective='regression', random_state=None,
       reg_alpha=0.0, reg_lambda=0.0, silent=True, subsample=1.0,
       subsample_for_bin=200000, subsample_freq=0)

In [10]:
y_pred = gbm.predict(X_test)
print(rmsle_metric(y_test, y_pred))

('RMSLE', 1.3886084257523357, False)


In [11]:
test = pd.read_csv('data/test.csv', index_col=0)
test.head()

48df886f9  0deb4b6a8  34b15f335  a8cb14b00  2f0771a37  30347e683  \
ID                                                                            
000137c73        0.0        0.0        0.0        0.0        0.0        0.0   
00021489f        0.0        0.0        0.0        0.0        0.0        0.0   
0004d7953        0.0        0.0        0.0        0.0        0.0        0.0   
00056a333        0.0        0.0        0.0        0.0        0.0        0.0   
00056d8eb        0.0        0.0        0.0        0.0        0.0        0.0   

           d08d1fbe3  6ee66e115  20aa07010  dc5a8f1d8    ...      3ecc09859  \
ID                                                       ...                  
000137c73        0.0        0.0        0.0        0.0    ...            0.0   
00021489f        0.0        0.0        0.0        0.0    ...            0.0   
0004d7953        0.0        0.0        0.0        0.0    ...            0.0   
00056a333        0.0        0.0        0.0        0.0    ...            0.0   
00056d8eb        0.0        0.0        0.0        0.0    ...            0.0   

           9281abeea  8675bec0b  3a13ed79a  f677d4d13  71b203550  137efaa80  \
ID                                                                            
000137c73        0.0        0.0        0.0        0.0        0.0        0.0   
00021489f        0.0        0.0        0.0        0.0        0.0        0.0   
0004d7953        0.0        0.0        0.0        0.0        0.0        0.0   
00056a333        0.0        0.0        0.0        0.0        0.0        0.0   
00056d8eb        0.0        0.0        0.0        0.0        0.0        0.0   

           fb36b89d9  7e293fbaf  9fc776466  
ID                                          
000137c73        0.0        0.0        0.0  
00021489f        0.0        0.0        0.0  
0004d7953        0.0        0.0        0.0  
00056a333        0.0        0.0        0.0  
00056d8eb        0.0        0.0        0.0  

[5 rows x 4991 columns]

In [12]:
ids = test.reset_index()['ID']

In [13]:
from sklearn.decomposition import FactorAnalysis
from sklearn.random_projection import GaussianRandomProjection
from sklearn.random_projection import SparseRandomProjection

X_fa = fa.transform(test)

X_srp = srp.transform(test)

X_grp = grp.transform(test)

X_added = pd.concat([
    pd.DataFrame(X_fa),
    pd.DataFrame(X_srp),
    pd.DataFrame(X_grp),
], axis=1)

y_pred = gbm.predict(X_added)
y_pred

array([13.95567088, 14.68080645, 14.47639788, ..., 14.70931812,
       13.23264655, 15.20740943])

In [16]:
y_pred = np.exp(y_pred) - 1

In [17]:
y_pred[0]

1150457.2263986063

In [18]:
ids[0]

'000137c73'

In [26]:
pd.DataFrame(y_pred, index=ids, columns=['target']).to_csv('data/submit.csv')